// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rakmbcoaustgusmipetx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJha21iY29hdXN0Z3VzbWlwZXR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MDQxMjcsImV4cCI6MjA2MjA4MDEyN30.WT4WfAnOOfkApgeObPtB_TiPdipDbushlOIm8341Xlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);